#server:
#  ssl:
#    key-store-type: PKCS12
#    key-store: classpath:certificate.p12
#    key-store-password: 1234

spring:
  datasource:
    url: jdbc:h2:mem:ssia
    username: sa
    password:
  sql:
    init: always

authorization:
  key: 1234
